stages:
  - build
  - deploy

build_wheel:
  stage: build
  image: python:3.6-slim
  tags:
  - build
  script:
  - pip wheel -w wheelhouse .
  artifacts:
    paths:
    - wheelhouse/*.whl

build_deb_amd64:
  stage: build
  image: moddevices/devtools:ub14-py34
  tags:
  - build
  before_script:
  - apt-get update -qq
  script:
  - apt-get install --no-install-recommends -qy libpcre3-dev devscripts pkg-config swig debhelper python3-numpy
  - ./build-python3-lilv.sh
  artifacts:
    paths:
    - ./*.deb
  only:
  - master

deploy_artifacts:
  stage: deploy
  environment: artifact_repo
  tags:
  - artifact_repo
  script:
  - cp -R wheelhouse/ /artifacts/
  - mkdir -p /artifacts/dpkg/
  - cp ./*.deb /artifacts/dpkg/
  only:
  - master
