stages:
  - build
  - publish

build_wheel:
  stage: build
  image: python:3.6-slim
  tags:
  - build
  script:
  - pip wheel -w wheelhouse .
  artifacts:
    paths:
    - wheelhouse/*.whl

build_deb_amd64:
  stage: build
  image: moddevices/devtools:ub14-py34
  tags:
  - build
  before_script:
  - apt-get update -qq
  script:
  - apt-get install --no-install-recommends -qy libpcre3-dev devscripts pkg-config swig debhelper python3-numpy
  - ./build-python3-lilv.sh
  artifacts:
    paths:
    - ./*.deb
  only:
  - master

publish_artifacts:
  stage: publish
  environment: artifacts_repo
  tags:
  - artifacts_repo
  before_script:
  - '! [ -d /artifacts ] && echo "Missing artifacts dir" && exit 1'
  script:
  - cd wheelhouse
  - |
      for wheel in *.whl; do
        d=$(echo $wheel | sed -r 's/([^-]*)-.*/\1/' | sed -r 's/[_]+/-/')
        mkdir -p /artifacts/wheelhouse/$d
        mv -f $wheel /artifacts/wheelhouse/$d/
      done
  - mkdir -p /artifacts/dpkg
  - cp ../*.deb /artifacts/dpkg/
  only:
  - master
